### ISSUE TITLE
Remove requests to gstatic

### ISSUE THREAD

**Issue by notnout** [yzernik/squeakroad#566]
Currently the market app is making clearnet requests to gstatic to get fonts. Nicer fonts are not worth the privacy implications this request has.

**Comment by yzernik** [comment]
Thanks @notnout.
I didn't notice that it was making any requests because the requests are happening inside the CSS file:
https://github.com/yzernik/squeakroad/blob/deff540d8f635abcc97216973e5652f634b79697/static/css/fonts.css#L6

Do you know if it's possible to get a static copy of the fonts saved locally?

**Comment by yzernik** [comment]
Fixed: https://github.com/yzernik/squeakroad/pull/570

Now all of the fonts are saved in the static directory.
